<?xml version="1.0" encoding="utf-8"?><Database Name="LibraryDatabase" Class="LibraryDbContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NOTEBOOK\SQLEXPRESS;Initial Catalog=LibraryDatabase;Integrated Security=True" SettingsObjectName="LibraryDatabase.Properties.Settings" SettingsPropertyName="LibraryDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Authors" Member="Authors">
    <Type Name="Author">
      <Column Name="AuthorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AuthorFirstName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorLastName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorBirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Author_Book" Member="Books" ThisKey="AuthorID" OtherKey="AuthorID" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Books" Member="Books">
    <Type Name="Book">
      <Column Name="BookID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AuthorID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GenreID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BookQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Author_Book" Member="Author" ThisKey="AuthorID" OtherKey="AuthorID" Type="Author" IsForeignKey="true" />
      <Association Name="Genre_Book" Member="Genre" ThisKey="GenreID" OtherKey="GenreID" Type="Genre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Genres" Member="Genres">
    <Type Name="Genre">
      <Column Name="GenreID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GenreName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Book" Member="Books" ThisKey="GenreID" OtherKey="GenreID" Type="Book" />
    </Type>
  </Table>
</Database>